fix: mark more fields as required - add ComputedUserset
openfga/api pull request #109
Opened 2023-10-27 17:10 UTC by rhamzeh

## Description

## References

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

2023-10-27 17:41 UTC, jpadilla approved these changes

2023-10-27 17:46 UTC, jon-whit requested changes
Are we following the protobuf best practices here with OUTPUT_ONLY vs REQUIRED fields? I'm not sure we are, and I'd us to verify that we are doing so.

Would you please post some links with best-practice guidance on the usage difference between these different options etc..?

2023-10-27 17:52 UTC, rhamzeh commented
@jon-whit feel free to do that change

2023-12-01 19:21 UTC, jon-whit approved these changes

2023-12-01 19:22 UTC, merged