docs: clarify self-defining usersets
openfga/api pull request #147
Opened 2024-03-28 01:21 UTC by miparnisari

## Description
Pre-requisite: https://github.com/openfga/openfga/pull/1066

In this PR I give examples of certain edge cases for the Check API.

2024-03-28 01:36 UTC, miparnisari commented on openfga/v1/openfga_service.proto
> +        "will return `{ \"allowed\": true }`, even though a specific user of the userset `group:finance#member` does not have the `reader` relationship with the given object.\n"
FWIW, this happens on `main` today. https://play.fga.dev/stores/create/?id=01HT1B1QQ96HZ44ZBVEVERX1E1

<img width="1508" alt="image" src="https://github.com/openfga/api/assets/5374887/77c75358-f91e-4939-8c4e-dc414cd8058f">

2024-03-28 15:19 UTC, jon-whit commented on openfga/v1/openfga_service.proto
> +        "```python\n"
Why python?

2024-03-28 15:24 UTC, jon-whit commented
This is a lot to digest to the eye. We should consider adding a healthy amount of whitespace and paragraphical separation.

<img width="1193" alt="Screenshot 2024-03-28 at 9 24 22 AM" src="https://github.com/openfga/api/assets/2899204/e870732b-3f9d-43e1-924b-a9de66837e7b">

2024-03-28 15:26 UTC, jon-whit submitted a review, later dismissed

2024-04-24 22:50 UTC, rhamzeh requested changes

2024-04-24 22:50 UTC, rhamzeh commented on openfga/v1/openfga_service.proto
> +        "The `user` field of the request can be a specific target, such as `user:anne`, or a userset (set of users) such as `user:*` or `group:marketing#member`.\n"
```suggestion
        "The `user` field of the request can be a specific target, such as `user:anne`, or a userset (set of users) such as `group:marketing#member` or a type-bound public access `user:*`.\n"
```

`user:*` is not a userset

2024-04-24 22:50 UTC, rhamzeh commented on openfga/v1/openfga_service.proto
> +        "To arrive at a result, the API uses: an authorization model, explicit tuples written through the Write API, and implicit tuples that exist by virtue of applying set theory.\n"
```suggestion
        "To arrive at a result, the API uses: an authorization model, explicit tuples written through the Write API, contextual tuples present in the request, and implicit tuples that exist by virtue of applying set theory (such as `document:2021-budget#viewer@document:2021-budget#viewer` - the set of users who are viewers of document:2021-budget are the set of users who are the viewers of document:2021-budget).\n"
```

2024-04-24 22:50 UTC, rhamzeh commented on openfga/v1/openfga_service.proto
> +        "In general, if a Check API responds with `{allowed: true}`, then you can expect the equivalent ListObjects query to return the object, and viceversa. \n"
Should we note that some exceptions apply?

e.g. ListObjects only returns tuples that it can compute within a time-frame?

2024-04-24 22:50 UTC, rhamzeh commented on openfga/v1/openfga_service.proto
> +        "```python\n"
You remembered! ❤️

2024-04-24 22:50 UTC, rhamzeh commented on openfga/v1/openfga_service.proto
> +        "To arrive at a result, the API uses: an authorization model, explicit tuples written through the Write API, and implicit tuples that exist by virtue of applying set theory.\n"
```suggestion
        "To arrive at a result, the API uses: an authorization model, explicit tuples written through the Write API, contextual tuples present in the request, and implicit tuples that exist by virtue of applying set theory (such as `document:2021-budget#viewer@document:2021-budget#viewer` - the set of users who are viewers of document:2021-budget are the set of users who are the viewers of document:2021-budget).\n"
```

2024-04-25 00:22 UTC, rhamzeh approved these changes

2024-04-25 22:00 UTC, willvedd approved these changes
LGTM. Glad I'm seeing this, I'll make sure that I make these same adjustments in #144

2024-04-25 22:03 UTC, merged