CI: pre-commit swagger check
openfga/api pull request #199
Opened 2024-09-18 14:26 UTC by justincoh

## Description

This PR adds a pre-commit hook to check if the swagger docs need updating. It does the following:

1. If an update to a `.proto` file is being committed
2. Check if the `/docs` folder is also being committed
3. If `/docs` is being committed, hook exits successfully
4. If `/docs` is not being committed, remind the author to update the docs but also exit successfully (non-blocking)

https://github.com/user-attachments/assets/d0ae23fa-503e-4f3f-8721-2eec99b63d52

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

2024-09-18 14:30 UTC, justincoh commented on Makefile
> +buf-gen: init-hooks
Tracking a hook in a repo requires some finagling, this is the lowest-impact way I could think of accomplishing it. We will have to run `buf-gen`, so this change makes `init-hooks` a dependency of the `buf-gen`

2024-09-18 14:31 UTC, justincoh commented on README.md
> +make buf-gen
swapped this out to encourage people to use the make command so the hook is in place as early as possible

2024-09-18 14:54 UTC, justincoh commented on Makefile
> +	git config --local core.hooksPath .githooks/
Note: if you have your own personal hooks running in `.git/hooks`, they'll have to be copied into `.githooks` if you want them to run after this

2024-09-18 15:44 UTC, willvedd requested changes

2024-09-18 15:44 UTC, willvedd commented on .githooks/pre-commit
> +    result=$(git diff --cached --raw docs/)
**Request:** Lets check for more than just the docs. The generated Go types are just as important to track.

2024-09-18 20:16 UTC, willvedd submitted a review, later dismissed
Great job 👍

2024-09-19 13:54 UTC, jpadilla commented
✨ nice!

> We have a github action check for this scenario

I wonder if maybe the github action we have today can reuse the same logic introduced in the precommit script?

2024-09-19 20:04 UTC, willvedd approved these changes

2024-09-19 20:10 UTC, rhamzeh requested changes

2024-09-19 20:10 UTC, rhamzeh commented on .githooks/pre-commit
> +if [[ "$files" =~ \.proto ]]
Why are we checking if the proto files where changed?

You should run `make` in the CI and see if the result of that is _any_ changed file anywhere through `git diff-files --quiet`
if the exit code is 0, that means no changes and the docs match what should be generated, if the exit code is 1 then there are uncommited changes, so error

2024-09-19 20:22 UTC, rhamzeh commented
I deleted my comment b/c realized we're not modifying the github action in this PR.

In a follow up PR, can you fix that?

https://github.com/openfga/api/blob/main/.github/workflows/review.yaml#L33-L36

We don't need to limit to docs and protos, any change anywhere should error.

(not a big issue b/c at the moment, we're most likely to modify those files, but if that changes or e.g. someone updates go.mod manually and keeps go.sum not updated)

2024-09-19 22:23 UTC, merged